### ISSUE TITLE
Could you help upgrade the vulnerble dependency in shape-detection-jdla_0.0.2

### ISSUE THREAD

**Issue by JoeGardner000** [JosueDLA/ShapeDetection#1]
Hi, @JosueDLA , I'd like to report a vulnerability issue in **shape-detection-jdla_0.0.2**.
### Issue Description
I noticed that **shape-detection-jdla_0.0.2** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).

### Dependency Graph between Python and Shared Libraries
![image (6)](https://user-images.githubusercontent.com/103017573/161965467-021726f8-bfbe-4fd4-b553-dcd8d09d0c0e.png)

### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in release ***4.5.5.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
Could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
JoeGardner

**Comment by JosueDLA** [comment]
Hi @JoeGardner000 thanks for opening an issue, the dependencies have been updated in caf79ddc97888f69d829d84d2ee0a6599a7a5f2c.

Best regards
Josué de León
